language: rust
sudo: required
cache: cargo
install:
- make install

rust:
    - stable
    - nightly

env:
    global:
      - RUST_TEST_THREADS=1

matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true


script:
    - cargo build --all --exclude=spake2_demo
    - cargo test --all --exclude=spake2_demo
    - make test

notifications:
  email: false
