language: rust

rust:
    - stable
    - nightly

matrix:
   allow_failures:
       - rust: nightly
   fast_finish: true

cache: cargo

script:
    - cargo build --all --exclude=pairsona_spake2

notifications:
  email: false
