language: rust
sudo: required
cache: cargo
install:
- make install

env:
    global:
      - RUST_TEST_THREADS=1

matrix:
    include:
        - rust: stable
          env: CARGO_FMT_CHECK=true
        - rust: nightly
    allow_failures:
        - rust: nightly
    fast_finish: true

before_script:
    - |
        if [ "${CARGO_FMT_CHECK:-false}" = "true" ]; then
            rustup component add rustfmt-preview
        fi

script:
    - if [ "${CARGO_FMT_CHECK:-false}" = "true" ]; then cargo fmt -- --check; fi
    - cargo build --all
    - cargo test --all
    - make test

notifications:
  email: false
