# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_USER    - login info for docker hub
# DOCKER_PASS
#
version: 2.1
defaults:
    docker_login: &docker_login
        run:
            name: Login to Dockerhub
            command: |
                if [ "${DOCKER_USER}" == "" ] || [ "${DOCKER_PASS}" == "" ]; then
                    echo "Skipping Login to Dockerhub, no credentials."
                else
                    echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin
                fi

jobs:
  test:
    docker:
      - image: circleci/rust:latest
        auth:
            username: $DOCKER_USER
            password: $DOCKER_PASS
    steps:
      - checkout
      - run:
          name: Set up rust and do base checks
          command: |
            rustup install stable
            rustup default stable
            rustup update
            rustup component add rustfmt
            rustup component add clippy
            cargo install cargo-audit
            rustc --version
      - run:
          name: Do rust checks
          # ignoring RUSTSEC-2020-0041 -> sentry fix not yet available
          # ignoring RUSTSEC-2020-0049 -> fix is beta code
          command: |
            cargo audit --ignore RUSTSEC-2020-0041 --ignore RUSTSEC-2020-0049
            cargo clippy --all -- -D warnings
      - run:
          name: Do integration and unit tests
          command: |
            cargo test --all --verbose -- --nocapture
  build:
    docker:
      - image: docker:18.02.0-ce
        auth:
            username: $DOCKER_USER
            password: $DOCKER_PASS
    working_directory: /dockerflow
    steps:
      # workaround circleci's fallback git's "object not found" error w/ tag
      # builds
      - run:
          name: Install Docker build dependencies
          command: apk add --no-cache openssh-client git

      - checkout
      - setup_remote_docker
      - *docker_login
      - run:
          name: Create a version.json
          command: |
            # create a version.json per https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > version.json

      - run:
          name: Build Docker image
          command: docker build -t app:build .

      # save the built docker container into CircleCI's cache. This is
      # required since Workflows do not have the same remote docker instance.
      - run:
          name: docker save app:build
          command: mkdir -p /cache; docker save -o /cache/docker.tar "app:build"
      - save_cache:
          key: v1-{{ .Branch }}-{{ .Environment.CIRCLE_TAG }}-{{ epoch }}
          paths:
            - /cache/docker.tar


  deploy:
    docker:
      - image: docker:18.02.0-ce
        auth:
            username: $DOCKER_USER
            password: $DOCKER_PASS
    steps:
      - setup_remote_docker
      - *docker_login
      - restore_cache:
          key: v1-{{.Branch}}
      - run:
          name: Restore Docker image cache
          command: docker load -i /cache/docker.tar

      - run:
          name: Deploy to Dockerhub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              DOCKER_TAG="latest"
            fi

            if echo "${CIRCLE_BRANCH}" | grep '^feature\..*' > /dev/null; then
              DOCKER_TAG="${CIRCLE_BRANCH}"
            fi

            if [ -n "${CIRCLE_TAG}" ]; then
              DOCKER_TAG="$CIRCLE_TAG"
            fi

            if [ -n "${DOCKER_TAG}" ]; then
              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
              echo ${DOCKERHUB_REPO}:${DOCKER_TAG}
              docker tag app:build ${DOCKERHUB_REPO}:${DOCKER_TAG}
              docker images
              docker push "${DOCKERHUB_REPO}:${DOCKER_TAG}"
            else
              echo "Not pushing to dockerhub for tag=${CIRCLE_TAG} branch=${CIRCLE_BRANCH}"
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/

      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
